import { Hypergraph } from "./priority-traversal-types";

export const pulleyHypergraph: Hypergraph = {
  "0": {
    id: "0",
    displayName: "Pulley diagram",
    description:
      "A mechanical system consisting of pulleys, ropes, and weights.",
    descriptionTokens: {
      label: "",
      longDescription:
        ". A mechanical system consisting of pulleys, ropes, and weights.",
      shortDescription: "",
    },
    parents: [],
    children: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
    ],
    priority: 0,
  },
  "1": {
    id: "1",
    displayName: "Pulley System A",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0"],
    children: ["12", "8", "13"],
    priority: 0,
  },
  "2": {
    id: "2",
    displayName: "Pulley System B",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0"],
    children: ["14", "9", "15"],
    priority: 0,
  },
  "3": {
    id: "3",
    displayName: "Pulley System C",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0"],
    children: ["16", "10", "17"],
    priority: 0,
  },
  "4": {
    id: "4",
    displayName: "Weight W1",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "; Weight 4 units.",
      shortDescription: "",
    },
    parents: ["0", "18"],
    children: [],
    priority: 0,
  },
  "5": {
    id: "5",
    displayName: "Weight W2",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0", "23"],
    children: [],
    priority: 0,
  },
  "6": {
    id: "6",
    displayName: "Ceiling",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0", "20"],
    children: [],
    priority: 0,
  },
  "7": {
    id: "7",
    displayName: "Floor",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0", "24", "25"],
    children: [],
    priority: 0,
  },
  "8": {
    id: "8",
    displayName: "Pulley A",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["1", "19"],
    children: [],
    priority: 0,
  },
  "9": {
    id: "9",
    displayName: "Pulley B",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["2", "21"],
    children: [],
    priority: 0,
  },
  "10": {
    id: "10",
    displayName: "Pulley C",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["3", "22"],
    children: [],
    priority: 0,
  },
  "11": {
    id: "11",
    displayName: "Rope 1",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["19", "20"],
    children: [],
    priority: 0,
  },
  "12": {
    id: "12",
    displayName: "Rope 2",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["1", "18"],
    children: [],
    priority: 0,
  },
  "13": {
    id: "13",
    displayName: "Rope 3",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["1", "21"],
    children: [],
    priority: 0,
  },
  "14": {
    id: "14",
    displayName: "Rope 4",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["2", "24"],
    children: [],
    priority: 0,
  },
  "15": {
    id: "15",
    displayName: "Rope 5",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["2", "22"],
    children: [],
    priority: 0,
  },
  "16": {
    id: "16",
    displayName: "Rope 6",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["3", "25"],
    children: [],
    priority: 0,
  },
  "17": {
    id: "17",
    displayName: "Rope 7",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["3", "23"],
    children: [],
    priority: 0,
  },
  "18": {
    id: "18",
    displayName: "Hangs: Weight W1 hangs from Rope 2",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0"],
    children: ["4", "12"],
    priority: 0,
  },
  "19": {
    id: "19",
    displayName: "Hangs: Pulley A hangs from Rope 1",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0"],
    children: ["8", "11"],
    priority: 0,
  },
  "20": {
    id: "20",
    displayName: "Hangs: Rope 1 hangs from Ceiling",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0"],
    children: ["6", "11"],
    priority: 0,
  },
  "21": {
    id: "21",
    displayName: "Hangs: Pulley B hangs from Rope 3",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0"],
    children: ["9", "13"],
    priority: 0,
  },
  "22": {
    id: "22",
    displayName: "Hangs: Pulley C hangs from Rope 5",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0"],
    children: ["10", "15"],
    priority: 0,
  },
  "23": {
    id: "23",
    displayName: "Hangs: Weight W2 hangs from Rope 7",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0"],
    children: ["5", "17"],
    priority: 0,
  },
  "24": {
    id: "24",
    displayName: "Anchor: Rope 4 is anchored to Floor",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0"],
    children: ["14", "7"],
    priority: 0,
  },
  "25": {
    id: "25",
    displayName: "Anchor: Rope 6 is anchored to Floor",
    description: "",
    descriptionTokens: {
      label: "",
      longDescription: "",
      shortDescription: "",
    },
    parents: ["0"],
    children: ["16", "7"],
    priority: 0,
  },
};
